# config.py

RED_ATTENUATION = 0.4
GREEN_ATTENUATION = 0.7
BLUE_ATTENUATION = 1.0

HAZE_INTENSITY = 0.3
HAZE_COLOR = [0.7, 0.8, 1.0]  # normalized RGB

CONTRAST_REDUCTION = 0.9
BRIGHTNESS_SHIFT = 0.05

ENABLE_BLUR = True
BLUR_KERNEL = (3, 3)

ENABLE_DEPTH_GRADIENT = True